#cloud-config
vyos_config_commands:
- delete interfaces ethernet eth0 address 'dhcp'
- delete service ssh port '22'
- set interfaces ethernet eth0 address '147.75.34.119/28'
- set interfaces ethernet eth1 description 'external'
- set system host-name 'router01'
- set system domain-name 'my-v-world.local'
- set system name-server '8.8.8.8'
- set system name-server '8.8.4.4'
- set interfaces ethernet eth1 address '192.168.0.1/24'
- set interfaces ethernet eth1 description 'internal'
- set protocols static route 0.0.0.0/0 next-hop '147.75.34.113'
- set nat source rule 100 outbound-interface 'eth0'
- set nat source rule 100 source address '192.168.0.0/24'
- set nat source rule 100 translation address 'masquerade'
- set service dhcp-server shared-network-name LAN subnet 192.168.0.0/24 default-router '192.168.0.1'
- set service dhcp-server shared-network-name LAN subnet 192.168.0.0/24 dns-server '192.168.0.1'
- set service dhcp-server shared-network-name LAN subnet 192.168.0.0/24 domain-name 'my-v-world.local'
- set service dhcp-server shared-network-name LAN subnet 192.168.0.0/24 lease '86400'
- set service dhcp-server shared-network-name LAN subnet 192.168.0.0/24 range 0 start '192.168.0.10'
- set service dhcp-server shared-network-name LAN subnet 192.168.0.0/24 range 0 stop '192.168.0.250'
- set service dns forwarding cache-size '0'
- set service dns forwarding listen-address  '192.168.0.1'
- set service dns forwarding allow-from  '192.168.0.0/24'
- set service dns forwarding name-server '8.8.8.8'
- set service dns forwarding name-server '8.8.4.4'